name: flyyer-deploy-yarn

on:
  push:
    branches:
      - master
      - main

jobs:
  deploy:
    name: Deploy
    runs-on: ubuntu-latest

    env:
      FLYYER_KEY: ${{secrets.FLYYER_KEY}}
      NODE_ENV: production

    steps:
      - uses: actions/checkout@v2

      - name: Use Node.js 14.x
        uses: actions/setup-node@v1
        with:
          node-version: "14.x"

      - name: modules cache
        uses: actions/cache@v2
        with:
          path: "**/node_modules"
          key: ${{ runner.os }}-modules-${{ hashFiles('**/yarn.lock') }}

      - name: Install dependencies
        run: yarn install --production=false # force install devDependencies

      - name: Build production deck
        run: yarn run build

      - name: Publish to Flyyer.io
        run: yarn run deploy